import Head from "next/head";
import { Header } from "../components/Header";
import { Hero } from "../components/Hero";
import { About } from "../components/About";

export default function Home() {
  return (
    <div
      className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll
    z-0"
    >
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300&display=swap"
          rel="stylesheet"
        />{" "}
      </Head>

      {/*Header*/}
      <Header />
      {/*Hero*/}
      <section id="hero" className="snap-center">
        <Hero />
      </section>
      {/*About*/}
      <section id="about" className="snap-center">
        <About />
      </section>
      {/*Experience*/}

      {/*Skills*/}

      {/*Offer*/}
    </div>
  );
}
